import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  es: {
    'nav.dashboard': 'Dashboard',
    'nav.cartera': 'Cartera',
    'nav.teams': 'Equipos',
    'nav.calendar': 'Calendario',
    'nav.coaches': 'Entrenadores',
    'nav.settings': 'Configuración',
    'header.profile': 'Mi Perfil',
    'header.logout': 'Cerrar Sesión',
    'header.lang': 'Idioma',
    'nav.planning': 'Planificación',
    'nav.my_ficha': 'Mi Ficha',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.search': 'Buscar...',
    'common.all': 'Todos',
    'common.status': 'Estado',
    'common.actions': 'Acciones',
    'common.time': 'Hora',
    'common.location': 'Lugar',
    'calendar.official_venue': 'Sede oficial',
    'calendar.confirm_delete': '¿Eliminar este evento?',
    'calendar.no_observations': 'Sin observaciones',
    'finance.total_pending': 'Cartera Pendiente',
    'finance.pending': 'Por Recaudar',
    'finance.paid': 'Recaudado',
    'finance.effectiveness': 'Efectividad',
    'dash.total_players': 'Total Deportistas',
    'dash.active_teams': 'Equipos Activos',
    'dash.monthly_revenue': 'Recaudo Mensual',
    'players.name': 'Nombre',
    'players.document': 'Documento',
    'players.phone': 'Teléfono',
    'players.team': 'Equipo',
    'players.status': 'Estado',
    'calendar.title': 'Calendario Deportivo',
    'calendar.subtitle': 'Gestiona entrenamientos y eventos especiales de tus equipos.',
    'calendar.generate_trainings': 'Generar Entrenamientos',
    'calendar.new_event': 'Nuevo Evento',
    'calendar.filter_team': 'Filtrar por Equipo',
    'calendar.all_teams': 'Todos los Equipos',
    'calendar.coach_obs': 'Los entrenadores pueden agregar observaciones en cada entrenamiento generado.',
    'calendar.month': 'Mes',
    'calendar.week': 'Semana',
    'calendar.event_details': 'Detalles del Evento',
    'calendar.attendance_control': 'Control de Asistencia',
    'calendar.delete': 'Eliminar',
    'calendar.close': 'Cerrar',
    'calendar.attendance_summary': 'Resumen de Asistencia',
    'calendar.present': 'Presente',
    'calendar.absent': 'Ausente',
    'calendar.late': 'Tarde',
    'calendar.justified': 'Justificado',
    'calendar.pres': 'Pres.',
    'calendar.aus': 'Aus.',
    'calendar.players_invited': 'Jugadores / Invitados',
    'calendar.players': 'Jugadores',
    'calendar.notes': 'Notas / Observaciones',
    'calendar.save_attendance': 'Guardar Asistencia',
    'calendar.loading_list': 'Cargando listado...',
    'calendar.no_players': 'No hay jugadores vinculados a este evento.',
    'calendar.wallet_warning': '¡En Cartera! Comunícate',
    'calendar.optional_note': 'Nota opcional...',
    'calendar.training_modal_title': 'Generar Calendario de Entrenamiento',
    'calendar.training_modal_info': 'Esta acción generará sesiones de entrenamiento automáticas basadas en los días habilitados en el perfil de cada equipo.',
    'calendar.select_team': 'Seleccionar Equipo',
    'calendar.choose_team': 'Elegir equipo...',
    'calendar.start_date': 'Fecha Inicio',
    'calendar.end_date': 'Fecha Fin',
    'calendar.gen_observations': 'Observaciones Generales',
    'calendar.gen_obs_placeholder': "Indique temas generales como 'Enfoque táctico' o 'Preparación física'...",
    'calendar.generate_sessions': 'Generar Sesiones',
    'calendar.event_modal_title': 'Nuevo Evento Especial',
    'calendar.event_name': 'Nombre del Evento',
    'calendar.event_name_placeholder': 'Ej: Final Copa Navideña',
    'calendar.date': 'Fecha',
    'calendar.location': 'Lugar',
    'calendar.location_placeholder': 'Ej: Estadio Central',
    'calendar.start_time': 'Hora Inicio',
    'calendar.end_time': 'Hora Fin',
    'calendar.description': 'Descripción',
    'calendar.description_placeholder': 'Detalles del evento...',
    'calendar.assign_team_opt': 'Asignar a Equipo (Opcional)',
    'calendar.all_club': 'General / Todo el Club',
    'calendar.invite_specific_players': 'Invitar Jugadores Específicos',
    'calendar.selected': 'seleccionados',
    'calendar.searching_athletes': 'Buscando deportistas...',
    'calendar.no_players_found': 'No se encontraron jugadores para invitar.',
    'calendar.create_event': 'Crear Evento',
    'calendar.sessions_generated': 'sesiones generadas con éxito.',
    'calendar.training_error': 'Error al generar entrenamientos: ',
    'calendar.no_status_assigned': 'No has asignado ningún estado de asistencia.',
    'calendar.attendance_saved': 'Asistencia guardada con éxito.',
    'calendar.attendance_error': 'Error al guardar asistencia: ',
    'calendar.event_created': 'Evento especial creado con éxito.',
    'calendar.event_error': 'Error al guardar evento: ',
    'month.0': 'Enero', 'month.1': 'Febrero', 'month.2': 'Marzo', 'month.3': 'Abril', 'month.4': 'Mayo', 'month.5': 'Junio',
    'month.6': 'Julio', 'month.7': 'Agosto', 'month.8': 'Septiembre', 'month.9': 'Octubre', 'month.10': 'Noviembre', 'month.11': 'Diciembre',
    'day.0': 'Domingo', 'day.1': 'Lunes', 'day.2': 'Martes', 'day.3': 'Miércoles', 'day.4': 'Jueves', 'day.5': 'Viernes', 'day.6': 'Sábado',
    'calendar.type.entrenamiento': 'Entrenamiento',
    'calendar.type.evento': 'Evento',
    'planning.title': 'Planificación Deportiva',
    'planning.subtitle': 'Diseña y organiza tus sesiones de entrenamiento al detalle.',
    'planning.new_session': 'Nueva Sesión',
    'planning.session_title': 'Título de la Sesión',
    'planning.team': 'Equipo',
    'planning.date_time': 'Fecha y Hora',
    'planning.period': 'Periodo',
    'planning.week_no': 'Semana No.',
    'planning.session_no': 'Sesión No.',
    'planning.description': 'Descripción',
    'planning.objectives': 'Objetivos',
    'planning.add_objective': 'Agregar Objetivo',
    'planning.target_type': 'Tipo de Objetivo',
    'planning.phases': 'Fases',
    'planning.calentamiento': 'Calentamiento',
    'planning.principal': 'Parte Principal',
    'planning.vuelta_calma': 'Vuelta a la Calma',
    'planning.phase_description': 'Descripción de la fase (opcional)...',
    'planning.add_task': 'Agregar Tarea',
    'planning.general_notes': 'Notas Generales',
    'planning.notes_placeholder': 'Notas generales, observaciones, feedback...',
    'planning.complete_session': 'Finalizar Sesión',
    'planning.save_session': 'Guardar Planificación',
    'planning.error_notes_required': 'Se requiere una nota general para completar la sesión.',
    'planning.error_objectives_required': 'Debes marcar al menos un objetivo como cumplido.',
    'planning.periods.pretemporada': 'Pretemporada',
    'planning.periods.competencia': 'Competencia',
    'planning.periods.transicion': 'Transición',
    'planning.periods.preparatorio': 'Preparatorio',
    'planning.periods.recuperacion': 'Recuperación',
    'planning.types.tecnico': 'Técnico',
    'planning.types.tactico': 'Táctico',
    'planning.types.ofensivo': 'Ofensivo',
    'planning.types.defensivo': 'Defensivo',
    'planning.types.mental': 'Mental'
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.cartera': 'Billing',
    'nav.teams': 'Teams',
    'nav.calendar': 'Calendar',
    'nav.coaches': 'Coaches',
    'nav.settings': 'Settings',
    'header.profile': 'My Profile',
    'header.logout': 'Logout',
    'header.lang': 'Language',
    'nav.planning': 'Planning',
    'nav.my_ficha': 'My Profile',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.search': 'Search...',
    'common.all': 'All',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.time': 'Time',
    'common.location': 'Location',
    'calendar.official_venue': 'Official venue',
    'calendar.confirm_delete': 'Delete this event?',
    'calendar.no_observations': 'No observations',
    'finance.total_pending': 'Pending Balance',
    'finance.pending': 'To Collect',
    'finance.paid': 'Collected',
    'finance.effectiveness': 'Efficiency',
    'dash.total_players': 'Total Athletes',
    'dash.active_teams': 'Active Teams',
    'dash.monthly_revenue': 'Monthly Revenue',
    'players.name': 'Name',
    'players.document': 'Document',
    'players.phone': 'Phone',
    'players.team': 'Team',
    'players.status': 'Status',
    'calendar.title': 'Sports Calendar',
    'calendar.subtitle': 'Manage trainings and special events for your teams.',
    'calendar.generate_trainings': 'Generate Trainings',
    'calendar.new_event': 'New Event',
    'calendar.filter_team': 'Filter by Team',
    'calendar.all_teams': 'All Teams',
    'calendar.coach_obs': 'Coaches can add observations to each generated training.',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.event_details': 'Event Details',
    'calendar.attendance_control': 'Attendance Control',
    'calendar.delete': 'Delete',
    'calendar.close': 'Close',
    'calendar.attendance_summary': 'Attendance Summary',
    'calendar.present': 'Present',
    'calendar.absent': 'Absent',
    'calendar.late': 'Late',
    'calendar.justified': 'Justified',
    'calendar.pres': 'Pres.',
    'calendar.aus': 'Abs.',
    'calendar.players_invited': 'Players / Guests',
    'calendar.players': 'Players',
    'calendar.notes': 'Notes / Observations',
    'calendar.save_attendance': 'Save Attendance',
    'calendar.loading_list': 'Loading list...',
    'calendar.no_players': 'No players linked to this event.',
    'calendar.wallet_warning': 'In Debt! Contact',
    'calendar.optional_note': 'Optional note...',
    'calendar.training_modal_title': 'Generate Training Calendar',
    'calendar.training_modal_info': 'This action will generate automatic training sessions based on the enabled days in each team\'s profile.',
    'calendar.select_team': 'Select Team',
    'calendar.choose_team': 'Choose team...',
    'calendar.start_date': 'Start Date',
    'calendar.end_date': 'End Date',
    'calendar.gen_observations': 'General Observations',
    'calendar.gen_obs_placeholder': 'Indicate general topics like \'Tactical focus\' or \'Physical preparation\'...',
    'calendar.generate_sessions': 'Generate Sessions',
    'calendar.event_modal_title': 'New Special Event',
    'calendar.event_name': 'Event Name',
    'calendar.event_name_placeholder': 'e.g., Christmas Cup Final',
    'calendar.date': 'Date',
    'calendar.location': 'Location',
    'calendar.location_placeholder': 'e.g., Central Stadium',
    'calendar.start_time': 'Start Time',
    'calendar.end_time': 'End Time',
    'calendar.description': 'Description',
    'calendar.description_placeholder': 'Event details...',
    'calendar.assign_team_opt': 'Assign to Team (Optional)',
    'calendar.all_club': 'General / Whole Club',
    'calendar.invite_specific_players': 'Invite Specific Players',
    'calendar.selected': 'selected',
    'calendar.searching_athletes': 'Searching for athletes...',
    'calendar.no_players_found': 'No players found to invite.',
    'calendar.create_event': 'Create Event',
    'calendar.sessions_generated': 'sessions generated successfully.',
    'calendar.training_error': 'Error generating training sessions: ',
    'calendar.no_status_assigned': 'No attendance status assigned.',
    'calendar.attendance_saved': 'Attendance saved successfully.',
    'calendar.attendance_error': 'Error saving attendance: ',
    'calendar.event_created': 'Special event created successfully.',
    'calendar.event_error': 'Error saving event: ',
    'month.0': 'January', 'month.1': 'February', 'month.2': 'March', 'month.3': 'April', 'month.4': 'May', 'month.5': 'June',
    'month.6': 'July', 'month.7': 'August', 'month.8': 'September', 'month.9': 'October', 'month.10': 'November', 'month.11': 'December',
    'day.0': 'Sunday', 'day.1': 'Monday', 'day.2': 'Tuesday', 'day.3': 'Wednesday', 'day.4': 'Thursday', 'day.5': 'Friday', 'day.6': 'Saturday',
    'calendar.type.entrenamiento': 'Training',
    'calendar.type.evento': 'Event',
    'planning.title': 'Sports Planning',
    'planning.subtitle': 'Design and organize your training sessions in detail.',
    'planning.new_session': 'New Session',
    'planning.session_title': 'Session Title',
    'planning.team': 'Team',
    'planning.date_time': 'Date and Time',
    'planning.period': 'Period',
    'planning.week_no': 'Week No.',
    'planning.session_no': 'Session No.',
    'planning.description': 'Description',
    'planning.objectives': 'Objectives',
    'planning.add_objective': 'Add Objective',
    'planning.target_type': 'Objective Type',
    'planning.phases': 'Phases',
    'planning.calentamiento': 'Warm-up',
    'planning.principal': 'Main Phase',
    'planning.vuelta_calma': 'Cool-down',
    'planning.phase_description': 'Phase description (optional)...',
    'planning.add_task': 'Add Task',
    'planning.general_notes': 'General Notes',
    'planning.notes_placeholder': 'General notes, observations, feedback...',
    'planning.complete_session': 'Complete Session',
    'planning.save_session': 'Save Planning',
    'planning.error_notes_required': 'A general note is required to complete the session.',
    'planning.error_objectives_required': 'You must mark at least one objective as met.',
    'planning.periods.pretemporada': 'Preseason',
    'planning.periods.competencia': 'Competition',
    'planning.periods.transicion': 'Transition',
    'planning.periods.preparatorio': 'Preparatory',
    'planning.periods.recuperacion': 'Recovery',
    'planning.types.tecnico': 'Technical',
    'planning.types.tactico': 'Tactical',
    'planning.types.ofensivo': 'Offensive',
    'planning.types.defensivo': 'Defensive',
    'planning.types.mental': 'Mental'
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.cartera': 'Facturation',
    'nav.teams': 'Équipes',
    'nav.calendar': 'Calendrier',
    'nav.coaches': 'Entraîneurs',
    'nav.settings': 'Paramètres',
    'header.profile': 'Mon profil',
    'header.logout': 'Déconnexion',
    'header.lang': 'Langue',
    'nav.planning': 'Planification',
    'nav.my_ficha': 'Ma Fiche',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.search': 'Rechercher...',
    'common.all': 'Tous',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.time': 'Heure',
    'common.location': 'Lieu',
    'calendar.official_venue': 'Siège officiel',
    'calendar.confirm_delete': 'Supprimer cet événement ?',
    'calendar.no_observations': 'Sans observations',
    'finance.total_pending': 'Portefeuille En Attente',
    'finance.pending': 'À percevoir',
    'finance.paid': 'Perçu',
    'finance.effectiveness': 'Efficacité',
    'dash.total_players': 'Total Athlètes',
    'dash.active_teams': 'Équipes Actives',
    'dash.monthly_revenue': 'Revenu Mensuel',
    'players.name': 'Nom',
    'players.document': 'Document',
    'players.phone': 'Téléphone',
    'players.team': 'Équipe',
    'players.status': 'Statut',
    'calendar.title': 'Calendrier Sportif',
    'calendar.subtitle': 'Gérez les entraînements et événements spéciaux de vos équipes.',
    'calendar.generate_trainings': 'Générer Entraînements',
    'calendar.new_event': 'Nouvel Événement',
    'calendar.filter_team': 'Filtrer par Équipe',
    'calendar.all_teams': 'Toutes les Équipes',
    'calendar.coach_obs': 'Les entraîneurs peuvent ajouter des observations à chaque entraînement généré.',
    'calendar.month': 'Mois',
    'calendar.week': 'Semaine',
    'calendar.event_details': 'Détails de l\'Événement',
    'calendar.attendance_control': 'Contrôle des Présences',
    'calendar.delete': 'Supprimer',
    'calendar.close': 'Fermer',
    'calendar.attendance_summary': 'Résumé des Présences',
    'calendar.present': 'Présent',
    'calendar.absent': 'Absent',
    'calendar.late': 'En retard',
    'calendar.justified': 'Justifié',
    'calendar.pres': 'Prés.',
    'calendar.aus': 'Abs.',
    'calendar.players_invited': 'Joueurs / Invités',
    'calendar.players': 'Joueurs',
    'calendar.notes': 'Notes / Observations',
    'calendar.save_attendance': 'Enregistrer la Présence',
    'calendar.loading_list': 'Chargement de la liste...',
    'calendar.no_players': 'Aucun joueur lié à cet événement.',
    'calendar.wallet_warning': 'En portefeuille ! Contactez-le',
    'calendar.optional_note': 'Note optionnelle...',
    'calendar.training_modal_title': 'Générer le calendrier d\'entraînement',
    'calendar.training_modal_info': 'Cette action générera des séances d\'entraînement automatiques basées sur les jours activés dans le profil de chaque équipe.',
    'calendar.select_team': 'Sélectionner l\'équipe',
    'calendar.choose_team': 'Choisir l\'équipe...',
    'calendar.start_date': 'Date de début',
    'calendar.end_date': 'Date de fin',
    'calendar.gen_observations': 'Observations générales',
    'calendar.gen_obs_placeholder': 'Indiquez des sujets généraux comme \'Focus tactique\' ou \'Préparation physique\'...',
    'calendar.generate_sessions': 'Générer les sessions',
    'calendar.event_modal_title': 'Nouvel événement spécial',
    'calendar.event_name': 'Nom de l\'événement',
    'calendar.event_name_placeholder': 'Ex: Finale de la Coupe de Noël',
    'calendar.date': 'Date',
    'calendar.location': 'Lieu',
    'calendar.location_placeholder': 'Ex: Stade Central',
    'calendar.start_time': 'Heure de début',
    'calendar.end_time': 'Heure de fin',
    'calendar.description': 'Description',
    'calendar.description_placeholder': 'Détails de l\'événement...',
    'calendar.assign_team_opt': 'Assigner à une équipe (Optionnel)',
    'calendar.all_club': 'Général / Tout le club',
    'calendar.invite_specific_players': 'Inviter des joueurs spécifiques',
    'calendar.selected': 'sélectionnés',
    'calendar.searching_athletes': 'Recherche de sportifs...',
    'calendar.no_players_found': 'Aucun joueur trouvé à inviter.',
    'calendar.create_event': 'Créer l\'événement',
    'calendar.sessions_generated': 'sessions générées avec succès.',
    'calendar.training_error': 'Erreur lors de la génération des entraînements : ',
    'calendar.no_status_assigned': 'Aucun statut de présence assigné.',
    'calendar.attendance_saved': 'Présence enregistrée avec succès.',
    'calendar.attendance_error': 'Erreur lors de l\'enregistrement de la présence : ',
    'calendar.event_created': 'Événement spécial créé avec succès.',
    'calendar.event_error': 'Erreur lors de l\'enregistrement de l\'événement : ',
    'month.0': 'Janvier', 'month.1': 'Février', 'month.2': 'Mars', 'month.3': 'Avril', 'month.4': 'Mai', 'month.5': 'Juin',
    'month.6': 'Juillet', 'month.7': 'Août', 'month.8': 'Septembre', 'month.9': 'Octobre', 'month.10': 'Novembre', 'month.11': 'Décembre',
    'day.0': 'Dimanche', 'day.1': 'Lundi', 'day.2': 'Mardi', 'day.3': 'Mercredi', 'day.4': 'Jeudi', 'day.5': 'Vendredi', 'day.6': 'Samedi',
    'calendar.type.entrenamiento': 'Entraînement',
    'calendar.type.evento': 'Événement',
    'planning.title': 'Planification Sportive',
    'planning.subtitle': 'Concevez et organisez vos séances d\'entraînement en détail.',
    'planning.new_session': 'Nouvelle Séance',
    'planning.session_title': 'Titre de la Séance',
    'planning.team': 'Équipe',
    'planning.date_time': 'Date et Heure',
    'planning.period': 'Période',
    'planning.week_no': 'Semaine No.',
    'planning.session_no': 'Séance No.',
    'planning.description': 'Description',
    'planning.objectives': 'Objectifs',
    'planning.add_objective': 'Ajouter un Objectif',
    'planning.target_type': 'Type d\'Objectif',
    'planning.phases': 'Phases',
    'planning.calentamiento': 'Échauffement',
    'planning.principal': 'Phase Principale',
    'planning.vuelta_calma': 'Retour au Calme',
    'planning.phase_description': 'Description de la phase (optionnel)...',
    'planning.add_task': 'Ajouter une Tâche',
    'planning.general_notes': 'Notes Générales',
    'planning.notes_placeholder': 'Notes générales, observations, retours...',
    'planning.complete_session': 'Terminer la Séance',
    'planning.save_session': 'Enregistrer la Planification',
    'planning.error_notes_required': 'Une note générale est requise pour terminer la séance.',
    'planning.error_objectives_required': 'Vous devez marquer au moins un objectif comme atteint.',
    'planning.periods.pretemporada': 'Pré-saison',
    'planning.periods.competencia': 'Compétition',
    'planning.periods.transicion': 'Transition',
    'planning.periods.preparatorio': 'Préparatoire',
    'planning.periods.recuperacion': 'Récupération',
    'planning.types.tecnico': 'Technique',
    'planning.types.tactico': 'Tactique',
    'planning.types.ofensivo': 'Offensif',
    'planning.types.defensivo': 'Défensif',
    'planning.types.mental': 'Mental'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  // Cargar idioma de localStorage después del primer render para evitar desajustes de hidratación/SSR si aplica
  useEffect(() => {
    const saved = localStorage.getItem('app-language');
    if (saved && (saved === 'es' || saved === 'en' || saved === 'fr')) {
      setLanguage(saved as Language);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    // Si la traducción no existe en el idioma actual, buscar en español (como fallback) o retornar la llave
    const currentTranslations = translations[language] || translations['es'];
    return currentTranslations[key] || translations['es'][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  // No lanzar error aquí para evitar white screens si se llama accidentalmente fuera
  // Aunque lo ideal es que esté dentro, retornamos un objeto dummy si no hay contexto
  if (context === undefined) {
    return {
      language: 'es' as Language,
      setLanguage: () => {},
      t: (key: string) => key
    };
  }
  return context;
};
